QoL and a few bug fixes
nununo/ansible-role-proxmox-haos-install pull request #27
Opened 2022-05-30 05:03 UTC by lmilius

I had to make a few changes in order to get the created VM to boot properly, not sure if the vmdk is working for you but I kept getting stuck at the EFI shell. I was following this site to update to the q35 machine type and using the ova qcow2 image instead of the generic vmdk image. I was using [this guide](https://blog.habitats.tech/howto-install-home-assistant-ha-os-in-proxmox-ve-pve-71) to cross-reference the install steps with the tasks provided in this role.

Updates I made to make it boot:

- q35 machine type
- use qcow2 ova image instead of generic vmdk
  - This required the change from a zip to xz to unarchive the downloaded file
  - Also added the xz-utils package because of this change, running proxmox on a base Debian 10 does not have xz installed by default. Moved the package install to be before downloading the image
- Replace hard-coded vmid with variable

A couple of quality of life changes I made to hopefully improve the usability:

- Added variable for storage interface (I prefer to use the scsi0 interface, but kept the sata0 interface as the default variable)
- Removed the size when importing the disk because the image will be the size that it was configured with in the ova that is downloaded. Looks to be related to issue #10 and #11. Probably would need a separate task before the VM is started to resize the disk somehow but I will leave that for a later time. The qcow2 appears to be 32GB by default. When it was set to the vmdk and not booting, the disk was showing as 6GB no matter what I set the size to, could just be a difference in image types.
- Added task to start the VM once everything was configured. Maybe a future improvement would be to add a variable/condition to allow the user to disable this in the future? If you feel that functionality would be necessary from the start, I can look into adding that if needed.
- Added a task to cleanup the tmp directory that is created at the beginning. I had more than a few copies of the downloaded disk image by the time I was done testing :smile: 

Let me know if there is anything you would like me to change for this pull request. I have been on the search for an ansible role that deploys home assistant this way. My current setup has been running with the qcow2/ova image in a proxmox VM for about 2 years now and working great, glad to see there is a role out there that deploys in this configuration! Thanks!

2022-05-30 15:36 UTC, nununo requested changes
Hi @lmilius,

I'm so glad to know that someone found it useful. I made it for myself because I use Ansible to automate most of my infrastructure. When I needed to reinstall HA I took the opportunity to convert that old bash script into an Ansible playbook. At first I and had it stored on my internal repo. But then I thought that maybe someone would like to use it and decided to publish it on github. I'm glad I did.

Thanks for all the improvements! Can I ask you to update the `README` to reflect the changes you made?

2022-05-30 15:45 UTC, lmilius commented
Just added the two variables from the defaults into the readme, let me know if you notice anything else missing. Thanks!

2022-05-30 15:48 UTC, lmilius commented
Also, is there anything special that needs to be done to publish to ansible galaxy or does that happen automatically? I wasn't able to install it normally, so I just cloned it into the galaxy install directory to use it.

2022-05-30 15:51 UTC, merged

2022-05-30 15:52 UTC, nununo commented
Merged. Thanks!

2022-05-30 15:54 UTC, nununo commented
> Also, is there anything special that needs to be done to publish to ansible galaxy or does that happen automatically?
That's a good question. Let's wait and see :)

> I wasn't able to install it normally, so I just cloned it into the galaxy install directory to use it.
You weren't able to install directly from galaxy using `ansible-galaxy`? I wonder why.

How did you find it btw?

2022-05-30 19:56 UTC, lmilius commented
I ran across the repo on a google search looking for exactly this. I had originally found a similarly named one that was an archived repo (and can't seem to find it again) but found this one instead. 

When I try installing from ansible-galaxy, I keep getting the following not found error:
```bash
$ ansible-galaxy install nununo.proxmox-haos-install
Starting galaxy role install process
- downloading role 'proxmox-haos-install', owned by nununo
[WARNING]: - nununo.proxmox-haos-install was NOT installed successfully: - sorry, nununo.proxmox-haos-install was not found on https://galaxy.ansible.com/api/.
```
This is my first time using ansible-galaxy, so wasn't sure how the community roles get published and if they had to have recent pushes to be active, similar to dockerhub where images that don't get pulled will expire off over time.

2022-05-30 20:00 UTC, lmilius commented
Oops, just realized it needs to be underscores instead of dashes after looking at the `meta/main.yaml`, I just assumed it would be the same as the one in the example, but I guess that part is wrong as well, I'll put in a PR 😄

2022-05-31 08:50 UTC, nununo commented
Oh my. -_-_-_- thanks!

2022-05-31 08:54 UTC, nununo commented
It seems Galaxy must be updated manually. I logged in, went to my repo list and there was an import button next to each one.

I'm also still learning about all this...

I should probably also add version tags.